name: immich
services:
  database:
    cpu_shares: 90
    container_name: immich-postgres
    deploy:
      resources:
        limits:
          memory: 7994M
    environment:
      - PG_DATA=/var/lib/postgresql/data
      - POSTGRES_DB=immich
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
    hostname: immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/immich.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/immich/pgdata
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    ports: []
    devices: []
    cap_add: []
    command: []
    networks:
      - immich_network
    privileged: false
  immich-machine-learning:
    cpu_shares: 90
    container_name: immich-machine-learning
    deploy:
      resources:
        limits:
          memory: 7994M
    environment:
      - DB_DATABASE_NAME=casaos
      - DB_HOSTNAME=immich-postgres
      - DB_PASSWORD=casaos
      - DB_PORT=5432
      - DB_USERNAME=casaos
      - REDIS_HOSTNAME=immich-redis
    hostname: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.3.1
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/immich.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/immich/model-cache
        target: /cache
        bind:
          create_host_path: true
    ports: []
    devices: []
    cap_add: []
    command: []
    networks:
      - immich_network
    privileged: false
  immich-server:
    cpu_shares: 90
    container_name: immich-server
    depends_on:
      database:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 7994M
    environment:
      - DB_DATABASE_NAME=immich
      - DB_HOSTNAME=immich-postgres
      - DB_PASSWORD=casaos
      - DB_PORT=5432
      - DB_USERNAME=casaos
      - IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
      - REDIS_HOSTNAME=immich-redis
    hostname: immich-server
    image: ghcr.io/immich-app/immich-server:v2.3.1
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/immich.png
    ports:
      - mode: ingress
        target: 2283
        published: "2283"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/immich/upload
        target: /usr/src/app/upload
        bind:
          create_host_path: true
      - type: bind
        source: /Volumes/MINI_KING_1TB/STORAGE/SharedDrive/Photos
        target: /external/photos
    devices: []
    cap_add: []
    command: []
    networks:
      - immich_network
    privileged: false
  redis:
    cpu_shares: 90
    container_name: immich-redis
    deploy:
      resources:
        limits:
          memory: 7994M
    hostname: immich-redis
    image: redis:6.2.20-alpine@sha256:2185e741f4c1e7b0ea9ca1e163a3767c4270a73086b6bbea2049a7203212fb7f
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/immich.png
    restart: always
    ports: []
    volumes: []
    devices: []
    cap_add: []
    command: []
    environment: []
    networks:
      - immich_network
    privileged: false
networks:
  immich_network:
    name: immich_network
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  author: immich-app
  category: media
  description:
    en_us: Self-hosted photo and video storage.
  developer: immich-app
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/immich.png
  index: /
  is_uncontrolled: false
  main: immich-server
  port_map: "2283"
  scheme: http
  store_app_id: immich
  tagline:
    en_us: Immich
  thumbnail: ""
  title:
    custom: ""
    en_us: Immich
